version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: interview_analyzer_db
    environment:
      POSTGRES_DB: interview_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432" # <-- КРИТИЧНО: первая 5432 — это порт на Маке, вторая — в контейнере
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
