server.port=8080

spring.application.name=interview-analyzer

# Настройки базы данных PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/interview_db
spring.datasource.username=postgres
spring.datasource.password=postgres_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Настройки Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# Разрешаем загрузку тяжелых файлов (.mov / .mp4 до 500 мб)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

